package file

var MimeTypes = map[string]string{
	".au":     "audio/basic",
	".avi":    "video/msvideo, video/avi, video/x-msvideo",
	".bmp":    "image/bmp",
	".bz2":    "application/x-bzip2",
	".css":    "text/css",
	".dtd":    "application/xml-dtd",
	".doc":    "application/msword",
	".exe":    "application/octet-stream",
	".gz":     "application/x-gzip",
	".gif":    "image/gif",
	".hqx":    "application/mac-binhex40",
	".html":   "text/html",
	".jar":    "application/java-archive",
	".jpeg":   "image/jpeg",
	".jpg":    "image/jpeg",
	".js":     "application/x-javascript",
	".midi":   "audio/x-midi",
	".mp3":    "audio/mpeg",
	".mpeg":   "video/mpeg",
	".ogg":    "audio/vorbis, application/ogg",
	".pdf":    "application/pdf",
	".pl":     "application/x-perl",
	".png":    "image/png",
	".ppt":    "application/vnd.ms-powerpoint",
	".ps":     "application/postscript",
	".qt":     "video/quicktime",
	".ra":     "audio/x-pn-realaudio, audio/vnd.rn-realaudio",
	".ram":    "audio/x-pn-realaudio, audio/vnd.rn-realaudio",
	".rdf":    "application/rdf, application/rdf+xml",
	".rtf":    "application/rtf",
	".sgml":   "text/sgml",
	".sit":    "application/x-stuffit",
	".svg":    "image/svg+xml",
	".swf":    "application/x-shockwave-flash",
	".tar.gz": "application/x-tar",
	".tgz":    "application/x-tar",
	".tiff":   "image/tiff",
	".tsv":    "text/tab-separated-values",
	".txt":    "text/plain",
	".wav":    "audio/wav, audio/x-wav",
	".xls":    "application/vnd.ms-excel",
	".xml":    "application/xml",
	".zip":    "application/zip, application/x-compressed-zip",
}
